### ISSUE TITLE
修改完系统的limits.conf后还需要在nginx里进行配置

### ISSUE THREAD

**Issue by friparia** [bg6cq/nginx-centos-7#1]

**Comment by friparia** [comment]
配置项：[worker_rlimit_nofile](http://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile)

检查是否生效的方法：cat /proc/$pid/limits

**Comment by bg6cq** [comment]
谢谢提醒。
其实 limits.conf 修改了没什么用。

我单独写了个文档 https://github.com/bg6cq/ITTS/tree/master/app/nginx/nginx-opt
